name: Ejecutar bot Bombers

on:
  workflow_dispatch:        # Permite ejecutarlo manualmente desde GitHub
  schedule:
    # Se ejecuta cada 30 minutos, excluyendo el horario de 1:00h a 6:00h (hora de España, CEST/CET).
    # La expresión cron 'minuto hora día_del_mes mes día_de_la_semana'.
    # 0,30: En los minutos 0 y 30 de cada hora.
    # 4-22: De las 4:00h UTC a las 22:59h UTC.
    # Esto se traduce aproximadamente a 6:00h CEST a 00:59h CEST del día siguiente.
    - cron: '0,30 4-22 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar el bot
        env:
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
          MIN_DOTACIONS: "5"
          GEOCODER_USER_AGENT: bombers_bot.1.0
          IS_TEST_MODE: "true" # Mantenemos en true para que NO intente publicar en X, solo en Telegram
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python bombers_bot.py
